[package]
name = "csa-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
csa-core.workspace = true
toml.workspace = true
serde.workspace = true
chrono.workspace = true
which.workspace = true
anyhow.workspace = true
